### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by TehShrike** [ashnur/windows-chrome#2]
You should merge #1 and then run `npm publish`!

https://github.com/juliangruber/browser-run/issues/112

**Comment by ashnur** [comment]
Hi, thanks, I read that, but I am not sure if this approach would work at all. It gave me very inconsistent results. Perhaps you have been able to test it?

**Comment by TehShrike** [comment]
It launches Chrome and everything when I run it, and it closes Chrome when `kill` is called, so it must be pretty close at least!  There was an error in the tests, but I fixed it in #3 if you want to merge that.

If there's anything else you know of that needs done still (I don't know what the specs are), you should add it to the readme or make an issue or something so folks interesting in browser-run can see what the status is.
